[project]
name = "cuad-mistral-finetuning"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "mistral-common>=1.8.3",
    "mistralai>=1.9.3",
    "pydantic>=2.11.7",
]

[dependency-groups]
dev = [
    "ruff>=0.12.7",
]
